name: Recyclarr
version: "8.5.0"
slug: recyclarr
description: TRaSH-Guide Sync f√ºr Sonarr und Radarr
arch:
  - amd64
  - aarch64
options:
  sonarr_url: ""
  sonarr_apikey: ""
  radarr_url: ""
  radarr_apikey: ""
  quality_profiles: "HD-1080p"
  enable_hdr: false
  enable_dv: false
  enable_hdr10plus: false
  prefer_hq_groups: false
  block_x265_hd: false
  enable_atmos: false
  enable_truehd: false
schema:
  sonarr_url: str
  sonarr_apikey: str
  radarr_url: str
  radarr_apikey: str
  quality_profiles: str
  enable_hdr: bool
  enable_dv: bool
  enable_hdr10plus: bool
  prefer_hq_groups: bool
  block_x265_hd: bool
  enable_atmos: bool
  enable_truehd: bool
